[package]
name = "ytlr"
version.workspace = true
edition.workspace = true

[dependencies]
ytlr-core = { path = "../core" }
ytlr-engine = { path = "../engine" }
ytlr-service = { path = "../service" }
anyhow.workspace = true
clap.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
