[package]
name = "ytlr-desktop"
version.workspace = true
edition.workspace = true
build = "build.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
ytlr-core = { path = "../../../crates/core" }
ytlr-service = { path = "../../../crates/service" }
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-dialog = "2"
tauri-plugin-notification = "2"
tauri-plugin-opener = "2"
tauri-plugin-single-instance = "2"
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
tokio.workspace = true
